accountId: "756007437776"
region: "ap-southeast-1"
awsProfile: "default"

rds:
  name: "demo-cluster"
  engine: "aurora-mysql"
  family: "8.0"
  parameters:
    - key: character_set_server
      value: utf8